<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Asynchronous JavaScript</title>
</head>
<body>
    <h1>Asynchronous JavaScript</h1>
    <script>
        /*const second = () => {
            setTimeout(() => {
                console.log('Aysnc hello');
            }, 2000);
        }

        const first = () => {
            console.log('hello world');
            second();
            console.log('The end');
        }

        first();
        */
        //
        //
        // The following is an example of "Callback Hell" ie too many nested timeouts....
        //
        //function getRecipe () {
        //    setTimeout(() => {
        //        const recipeID = [343, 629, 937, 175];
        //        console.log(recipeID);
        //        //
        //        setTimeout(id => {
        //            const recipe = {title : 'Chicken Pasta', publisher : 'Sideshow Bob'};
        //            console.log(`${id} : ${recipe.title}`);
        //            //
        //            setTimeout(publisher => {
        //                const recipe2 = {title : 'Meat Feast Pizza', publisher : 'Sideshow Bob'};
        //                 console.log(recipe2);
        //            }, 1500, recipe.publisher);
        //        }, 1500, recipeID[3]);
        //    }, 2000);
        //}
        //
        //getRecipe();
        //
        //
        // Example of a 'Promise' these stop the callback hell....resolve and reject are standard names for when a promise works ok (resolved) or fails (reject).
        //
        /*const getIDs = new Promise((resolve, reject) => {
            setTimeout(() => {
                resolve([343, 629, 937, 175]);
            }, 1500);

        });
        //
        const getRecipe = recID => {
            return new Promise((resolve, reject) => {
                setTimeout((ID) => {
                    const recipe = {title : 'Chicken Pasta', publisher : 'Sideshow Bob'};
                    resolve(`${ID} : ${recipe.title}`);
                }, 1500, recID);
            });
        };
        //
        const getRelated = publisher => {
              return new Promise((resolve, reject) => {
                setTimeout((pub) => {
                    const recipe = {title : 'Meat Feast Pizza', publisher : 'Sideshow Bob'};
                    resolve(`${pub} : ${recipe.title}`);
                }, 1500, publisher);
            });
        };
        */
        // .then is when a promise is resolved (worked ok)
        // .catch is when a promise has not been resolved (it failed)
        //
        // Note - you can CHAIN methods as well, dont need to write getIDs.then {blah blah blah} followed by getIDs.catch{blah blah blah}  they can look like the below !!!!
        //
        // this is the ES6 way to CONSUME promises....
        /*getIDs
        .then(IDs => {
            console.log(IDs);
            return getRecipe(IDs[2]);
        })
        .then(recipe => {
            console.log(recipe);
            return getRelated('Sideshow Bob');
        })
        .then(recipe => {
            console.log(recipe);
        })
        .catch(error => {
            console.log('Error !!!');
        });
        */
        //
        // this is the ES8 way to consume promises....an asyncronous wait function (hence me putting AW at the end of the function name getRecipiesAW, which returns a promise.
        /*async function getRecipesAW() {
            const IDs = await getIDs;
            console.log(IDs);
            const recipe = await getRecipe(IDs[1]);
            console.log(recipe);
            const related = await getRelated('Sideshow Bob');
            console.log(related);
            //
            return recipe;
        }
        //
        //getRecipesAW();
        //
        // can use .then to 'consume the promise' as the asyncronous function getRecipeAW returns a promise !
        getRecipesAW().then(result => console.log(`${result} is just brilliant`));
        */
        //
        //
        //
        // Making AJAX calls using FETCH and PROMISES...
        // Using this will give us a error due to javascript not allowing "cross origin" policy, ie  we cant access someone elses data which is on a different server to that of our own server...
        //fetch('https://www.metaweather.com/api/location/2487956/');
        //
        // Below is a workaround, using "crossorigin.me" we can chanel our request via them....
        /*
        function getWeather(woeid) {
            fetch(`https://cors-anywhere.herokuapp.com/https://www.metaweather.com/api/location/${woeid}/`)
            .then(result => {
        //        console.log(`the result is ${result}.`);
                return result.json();
            })
            .then(data => {
                //console.log(data);
                const today = data.consolidated_weather[0];
                console.log(`Temperatures today in ${data.title} stay betwee ${today.min_temp} and ${today.max_temp}.`);
            })
            .catch(error => console.log(`we have an error ${error}.`));
        }
        //
        getWeather(2487956);
        getWeather(44418);
        */
        //
        //  Same as above but using an async await function.
        async function getWeatherAW(woeid) {
            try {
                const result = await fetch(`https://cors-anywhere.herokuapp.com/https://www.metaweather.com/api/location/${woeid}/`);
                const data = await result.json();
                const tomorrow = data.consolidated_weather[1];
                console.log(`Temperatures tomorrow in ${data.title} stay between  ${tomorrow.min_temp} and ${tomorrow.max_temp}.`);
                return data;
            } catch(error) {
                //console.log(error);
                // Use alert to pop up a dialogue box as opposed to a log message..
                alert(error);
            }
        }
        //
        getWeatherAW(2487956);
        //
        // different way to call the function and get the result...
        let dataLondon;
        //
        getWeatherAW(44418).then(data => {
            dataLondon = data;
            console.log(dataLondon);
        });
        //
        //
        //
    </script>
</body>
</html>































